version: "3"
services:  
  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "8080:5000"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./babylonproject
    restart: always    
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./babylonproject:/app
      - ./babylonproject/dist:/app/dist
