apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: https://us-ashburn-1.ocir.io/<DOCKER_OBJECT_STORAGE_NAMESPACE>/babylon-backend:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: babylon-secret