FROM node:18-alpine
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install -g nodemon
RUN npm install react-scripts@5.0.1 -g --silent
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
CMD ["npm", "run", "start"]